# Numpy

In [2]:
import numpy as np

Creating arrays

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
b = np.array([1,2.3,"abc",True])

In [6]:
b

array(['1', '2.3', 'abc', 'True'], dtype='<U32')

# Properties of an array

In [7]:
a1 = np.array([10,20,30,40])

In [8]:
a1

array([10, 20, 30, 40])

In [9]:
a1.ndim

1

In [10]:
a1.dtype

dtype('int32')

In [11]:
a1.shape

(4,)

In [12]:
a1.size

4

In [13]:
a1.itemsize

4

# Different ways of creating array

In [14]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [15]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
np.array(np.random.randn(5),dtype='int')

array([-2,  1,  3,  0,  0])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.ones(3)

array([1., 1., 1.])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.array([1,2,3],dtype='float')

array([1., 2., 3.])

# Multi dimensional array

In [28]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

In [30]:
np.arange(10,20).reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
np.array([[2,3,4],[5,6,7]]).reshape(6,)

array([2, 3, 4, 5, 6, 7])

In [4]:
a = np.random.randn(24).reshape(2,3,4)

In [5]:
a

array([[[-0.428482  ,  1.87241812,  0.58256822,  0.59220485],
        [-0.68177143, -0.79809588, -1.75805269, -0.16693394],
        [-2.01195778,  0.19262143,  1.23915994, -0.48944147]],

       [[-1.37516243, -0.07910982,  1.35803138, -0.05097646],
        [ 1.05081938, -0.98668714, -0.14311265,  0.17327812],
        [-0.05818404, -0.47850141,  0.63401969, -1.4997928 ]]])

In [6]:
a.dtype

dtype('float64')

In [7]:
a.itemsize

8

In [8]:
a.size

24

In [9]:
a.shape

(2, 3, 4)

In [10]:
a.ndim

3

# Array Functions

In [11]:
a = np.arange(10,20).reshape(2,5)

In [12]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
a.sum()

145

In [14]:
a.sum(axis=0)

array([25, 27, 29, 31, 33])

In [15]:
a.sum(axis=1)

array([60, 85])

In [16]:
a.max()

19

In [17]:
a.min()

10

In [18]:
a

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
a.max(axis=1)

array([14, 19])

In [20]:
a.max(axis=0)

array([15, 16, 17, 18, 19])

In [21]:
a.mean()

14.5

In [22]:
a.var()

8.25

In [23]:
a.std()

2.8722813232690143

# Numpy functions

In [24]:
a = np.array([1,1,2,2,2,2,2,3,3,3,4,4,5,6,7,8,9])

In [25]:
a

array([1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5, 6, 7, 8, 9])

In [26]:
np.mean(a)

3.764705882352941

In [27]:
np.median(a)

3.0

In [35]:
q1 = np.quantile(a,0.25)

In [36]:
q3 = np.quantile(a,0.75)

In [37]:
iqr = q3 - q1 

In [38]:
iqr

3.0

In [39]:
upper_range = q3 + 1.5*iqr

In [40]:
lower_range = q1 - 1.5*iqr

In [41]:
upper_range

6.5

In [42]:
lower_range

-2.5

# Math functions

In [43]:
np.sin(90)

0.8939966636005579

In [44]:
np.cos(90)

-0.4480736161291701

In [45]:
np.log(10)

2.302585092994046

In [46]:
np.log(1)

0.0

In [47]:
np.log10(10)

1.0

In [48]:
np.log(np.log10(5))

-0.35814744992084513

In [49]:
np.sqrt(144)

12.0

# Reducing skewness

In [50]:
a = np.array([1,2,2,3,3,3,4,4,16,20,25])

In [51]:
a

array([ 1,  2,  2,  3,  3,  3,  4,  4, 16, 20, 25])

In [52]:
np.mean(a)

7.545454545454546

In [53]:
np.median(a)

3.0

In [55]:
from scipy.stats import skew

In [56]:
skew(a)

1.1712731595847037

In [57]:
a = np.sqrt(a)

In [58]:
a

array([1.        , 1.41421356, 1.41421356, 1.73205081, 1.73205081,
       1.73205081, 2.        , 2.        , 4.        , 4.47213595,
       5.        ])

In [59]:
skew(a)

0.9630668329521322

In [61]:
a1 = np.arange(10,16).reshape(3,2)

In [63]:
a2 = np.arange(16,22).reshape(3,2)

In [64]:
a1

array([[10, 11],
       [12, 13],
       [14, 15]])

In [65]:
a2

array([[16, 17],
       [18, 19],
       [20, 21]])

In [67]:
np.concatenate([a1,a2])

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [68]:
np.concatenate([a1,a2],axis=1)

array([[10, 11, 16, 17],
       [12, 13, 18, 19],
       [14, 15, 20, 21]])

In [69]:
np.unique([1,1,2,3])

array([1, 2, 3])

In [70]:
np.unique([1,1,2,3],return_counts=True)

(array([1, 2, 3]), array([2, 1, 1], dtype=int64))

# Indexing and Slicing

In [72]:
a = np.arange(10,20).reshape(5,2)

In [73]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [74]:
a[1]

array([12, 13])

In [75]:
a[1,1]

13

In [76]:
a[1][1]

13

In [77]:
a[2:4,]

array([[14, 15],
       [16, 17]])

In [78]:
a[2:4,0:2]

array([[14, 15],
       [16, 17]])

In [79]:
a[2:4,1]

array([15, 17])

In [84]:
a[2,0]

14

In [85]:
a[3,1]

17

In [89]:
a[[0,2]]

array([[10, 11],
       [14, 15]])

In [91]:
a[[0,2],1]

array([11, 15])

In [92]:
a[[0,2],0]

array([10, 14])

# Boolean indexing

In [93]:
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [94]:
a > 15

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [95]:
a[a>15]

array([16, 17, 18, 19])

In [96]:
a[a % 2 == 0]

array([10, 12, 14, 16, 18])

# Vectorization

In [101]:
a = np.array([1,2,3])

In [102]:
s = 10

In [103]:
a+s

array([11, 12, 13])

In [104]:
np.array([2,3,4]) * 10

array([20, 30, 40])

# Broadcasting

In [105]:
a1 = np.array([[1,2],[3,4]])

In [106]:
a2 = np.array([2,3])

In [107]:
a1

array([[1, 2],
       [3, 4]])

In [108]:
a2

array([2, 3])

In [109]:
a1 + a2

array([[3, 5],
       [5, 7]])

# Cross vs Dot product

In [110]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])

In [111]:
a1

array([[1, 2],
       [3, 4]])

In [112]:
a2

array([[5, 6],
       [7, 8]])

In [113]:
# cross product
a1*a2

array([[ 5, 12],
       [21, 32]])

In [114]:
# dot product
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])