In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

In [7]:
df = pd.read_csv("cars.csv")

In [8]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
symboling            205 non-null int64
normalized-losses    205 non-null object
make                 205 non-null object
fuel-type            205 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
width                205 non-null float64
height               205 non-null float64
engine-type          205 non-null object
engine-size          205 non-null int64
horsepower           205 non-null object
city-mpg             205 non-null int64
highway-mpg          205 non-null int64
price                205 non-null int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [10]:
df["normalized-losses"].replace("?",np.nan,inplace=True)
df["normalized-losses"] = df["normalized-losses"].astype(float)
losses_mean = df["normalized-losses"].mean()
df["normalized-losses"].fillna(losses_mean,inplace=True)

In [11]:
df["horsepower"].replace("?",np.nan,inplace=True)
df["horsepower"] = df["horsepower"].astype(float)
horsepower_mean = df["horsepower"].mean()
df["horsepower"].fillna(horsepower_mean,inplace=True)

In [12]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [13]:
df_num = df.select_dtypes(["int64","float64"])
df_cat = df.select_dtypes("object")

In [14]:
df_num.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [15]:
df_cat.head()

make fuel-type   body-style drive-wheels engine-location engine-type
0  alfa-romero       gas  convertible          rwd           front        dohc
1  alfa-romero       gas  convertible          rwd           front        dohc
2  alfa-romero       gas    hatchback          rwd           front        ohcv
3         audi       gas        sedan          fwd           front         ohc
4         audi       gas        sedan          4wd           front         ohc

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
for col in df_cat:
    le = LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])

In [18]:
df_cat.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [19]:
df_new = pd.concat([df_num,df_cat],axis=1)

In [20]:
df_new.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg  price  make  fuel-type  body-style  drive-wheels  \
0        21           27  13495     0          1           0             2   
1        21           27  16500     0          1           0             2   
2        19           26  16500     0          1           2             2   
3        24           30  13950     1          1           3             1   
4        18           22  17450     1          1           3             0   

   engine-location  engine-type  
0                0            0  
1                0            0  
2                0            5  
3                0            3  
4                0            3

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [22]:
X = df_new.drop("price",axis=1)
y = df["price"]

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [24]:
lin = LinearRegression()

lin.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
# Train score
lin.score(X_train,y_train)

0.8504573774895473

In [26]:
# Test score
lin.score(X_test,y_test)

0.7965566780397383

In [27]:
lin.coef_

array([ 4.51384957e+01,  1.53127607e+00,  7.89452171e+02,  3.62663990e+02,
        9.83682875e+01, -1.08169245e+01,  3.08017854e+02, -4.17024371e+02,
       -2.00099087e+02, -6.22650015e+02, -1.70235175e+02,  1.86860719e+03,
        1.64133620e+04,  2.83174279e+02])

In [28]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [29]:
# Ridge
l2 = Ridge(10)
l2.fit(X_train,y_train)
l2.coef_

array([ 2.08658930e+02, -5.60173023e-01,  3.64420144e+02,  5.72916414e+02,
        1.04441215e+02,  2.21332730e+01,  2.11271281e+02, -2.72864381e+02,
       -1.86340249e+02, -9.06610516e+02, -6.30655861e+02,  1.56860422e+03,
        2.57047785e+03,  5.15948757e+02])

In [30]:
# Lasso helps in feature selection
l1 = Lasso(1000)
l1.fit(X_train,y_train)
l1.coef_

array([   0.        ,    3.96310671,    0.        ,  276.93279232,
        135.34169218,   16.00129073,   -0.        , -113.03311963,
       -126.40695244,   -0.        ,   -0.        ,    0.        ,
          0.        ,    0.        ])

In [31]:
for i in range(50):
    l2 = Ridge(alpha=i)
    l2.fit(X_train,y_train)
    print(i,":",l2.score(X_test,y_test))

0 : 0.7965566780397386
1 : 0.8074518758147277
2 : 0.8110292248150517
3 : 0.8126933383890037
4 : 0.81361486450293
5 : 0.8141745853539419
6 : 0.8145301242133359
7 : 0.8147582608502817
8 : 0.8149010602831955
9 : 0.8149836949253051
10 : 0.8150222867376529
11 : 0.8150277245431791
12 : 0.8150076788279422
13 : 0.8149677381788262
14 : 0.8149120868051174
15 : 0.8148439278252525
16 : 0.8147657584947392
17 : 0.8146795554128127
18 : 0.8145869029046838
19 : 0.8144890843369585
20 : 0.8143871485445552
21 : 0.8142819591129828
22 : 0.8141742315788492
23 : 0.8140645619421543
24 : 0.8139534488166061
25 : 0.8138413108452037
26 : 0.8137285005403767
27 : 0.8136153153884842
28 : 0.8135020068362638
29 : 0.8133887876197217
30 : 0.8132758377831449
31 : 0.813163309653795
32 : 0.8130513319772293
33 : 0.8129400133729978
34 : 0.8128294452363019
35 : 0.8127197041851856
36 : 0.8126108541327799
37 : 0.8125029480485764
38 : 0.8123960294605082
39 : 0.8122901337400306
40 : 0.8121852892047275
41 : 0.8120815180669063
42 : 

In [32]:
for i in range(200,500,50):
    l1 = Lasso(alpha=i)
    l1.fit(X_train,y_train)
    print(i,":",l1.score(X_test,y_test))

200 : 0.8139201358023782
250 : 0.8124219090780234
300 : 0.8085057299003378
350 : 0.8036053753129062
400 : 0.7977229768452246
450 : 0.7950465607641614


In [33]:
# Final models
l2 = Ridge(alpha=2)
l2.fit(X_train,y_train)
print(l2.score(X_test,y_test))

0.8110292248150517


In [34]:
l2.coef_

array([ 1.66477241e+02, -8.84331252e-01,  5.06201386e+02,  5.02070806e+02,
        1.00154543e+02,  1.04124700e+01,  2.44076984e+02, -3.27713737e+02,
       -1.94641841e+02, -1.13894088e+03, -4.80922921e+02,  1.88121378e+03,
        7.76076971e+03,  4.65928529e+02])

In [35]:
l1 = Lasso(alpha=200)
l1.fit(X_train,y_train)
print(l1.score(X_test,y_test))

0.8139201358023782


In [36]:
l1.coef_

array([ 0.00000000e+00,  2.07002782e+00,  3.23427588e+02,  4.69420186e+02,
        1.15553544e+02,  1.42784033e+01,  3.62975615e+01, -1.24776284e+02,
       -1.67461354e+02, -0.00000000e+00, -4.05115132e+02,  1.11242794e+03,
        2.09462838e+03,  3.05815537e+02])

## Cross validation

In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
l1_cross = cross_val_score(l1,X,y,cv=4)

In [39]:
l1_cross

array([0.76560829, 0.81872367, 0.43344753, 0.448364  ])

In [40]:
l2_cross = cross_val_score(l2,X,y,cv=4)

In [41]:
l2_cross

array([0.71176474, 0.86474228, 0.37640664, 0.47020196])

In [42]:
np.mean(l1_cross)

0.6165358705430692

In [43]:
np.mean(l2_cross)

0.6057789059244743