# Regularization

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("Automobile_data.csv")

In [4]:
df.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
symboling            205 non-null int64
normalized-losses    205 non-null object
make                 205 non-null object
fuel-type            205 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
width                205 non-null float64
height               205 non-null float64
engine-type          205 non-null object
engine-size          205 non-null int64
horsepower           205 non-null object
city-mpg             205 non-null int64
highway-mpg          205 non-null int64
price                205 non-null int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [6]:
df["normalized-losses"].replace("?",np.nan,inplace=True)
df["normalized-losses"] = df["normalized-losses"].astype(float)
losses_mean = df["normalized-losses"].mean()
df["normalized-losses"].fillna(losses_mean,inplace=True)

In [7]:
df["horsepower"].replace("?",np.nan,inplace=True)
df["horsepower"] = df["horsepower"].astype(float)
horsepower_mean = df["horsepower"].mean()
df["horsepower"].fillna(horsepower_mean,inplace=True)

In [8]:
df.dtypes

symboling              int64
normalized-losses    float64
make                  object
fuel-type             object
body-style            object
drive-wheels          object
engine-location       object
width                float64
height               float64
engine-type           object
engine-size            int64
horsepower           float64
city-mpg               int64
highway-mpg            int64
price                  int64
dtype: object

In [9]:
df_num = df.select_dtypes(["int64","float64"])
df_cat = df.select_dtypes("object")

In [10]:
df_num.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

In [11]:
df_cat.head()

make fuel-type   body-style drive-wheels engine-location engine-type
0  alfa-romero       gas  convertible          rwd           front        dohc
1  alfa-romero       gas  convertible          rwd           front        dohc
2  alfa-romero       gas    hatchback          rwd           front        ohcv
3         audi       gas        sedan          fwd           front         ohc
4         audi       gas        sedan          4wd           front         ohc

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
for col in df_cat:
    le = LabelEncoder()
    df_cat[col] = le.fit_transform(df_cat[col])

C:\Users\itvedant-le1\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [14]:
df_cat.head()

make  fuel-type  body-style  drive-wheels  engine-location  engine-type
0     0          1           0             2                0            0
1     0          1           0             2                0            0
2     0          1           2             2                0            5
3     1          1           3             1                0            3
4     1          1           3             0                0            3

In [15]:
df_new = pd.concat([df_num,df_cat],axis=1)

In [16]:
df_new.head()

symboling  normalized-losses  width  height  engine-size  horsepower  \
0          3              122.0   64.1    48.8          130       111.0   
1          3              122.0   64.1    48.8          130       111.0   
2          1              122.0   65.5    52.4          152       154.0   
3          2              164.0   66.2    54.3          109       102.0   
4          2              164.0   66.4    54.3          136       115.0   

   city-mpg  highway-mpg  price  make  fuel-type  body-style  drive-wheels  \
0        21           27  13495     0          1           0             2   
1        21           27  16500     0          1           0             2   
2        19           26  16500     0          1           2             2   
3        24           30  13950     1          1           3             1   
4        18           22  17450     1          1           3             0   

   engine-location  engine-type  
0                0            0  
1                0            0  
2                0            5  
3                0            3  
4                0            3

### Baseline model

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [18]:
X = df_new.drop("price",axis=1)
y = df["price"]

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [20]:
lin = LinearRegression()

lin.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
lin.score(X_test,y_test)

0.7965566780397383

In [22]:
lin.coef_

array([ 4.51384957e+01,  1.53127607e+00,  7.89452171e+02,  3.62663990e+02,
        9.83682875e+01, -1.08169245e+01,  3.08017854e+02, -4.17024371e+02,
       -2.00099087e+02, -6.22650015e+02, -1.70235175e+02,  1.86860719e+03,
        1.64133620e+04,  2.83174279e+02])

## Lasso (L1) and Ridge (L2) Regularization

In [23]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [24]:
for i in range(50):
    l2 = Ridge(alpha=i)
    l2.fit(X_train,y_train)
    print(i,":",l2.score(X_test,y_test))

0 : 0.7965566780397376
1 : 0.8074518758147271
2 : 0.8110292248150516
3 : 0.8126933383890029
4 : 0.8136148645029299
5 : 0.8141745853539419
6 : 0.8145301242133356
7 : 0.8147582608502816
8 : 0.8149010602831955
9 : 0.8149836949253052
10 : 0.8150222867376533
11 : 0.8150277245431791
12 : 0.8150076788279416
13 : 0.8149677381788258
14 : 0.8149120868051176
15 : 0.8148439278252515
16 : 0.814765758494739
17 : 0.8146795554128126
18 : 0.8145869029046835
19 : 0.8144890843369585
20 : 0.8143871485445551
21 : 0.8142819591129827
22 : 0.8141742315788496
23 : 0.8140645619421543
24 : 0.813953448816606
25 : 0.8138413108452037
26 : 0.8137285005403768
27 : 0.8136153153884843
28 : 0.8135020068362637
29 : 0.8133887876197211
30 : 0.813275837783145
31 : 0.813163309653795
32 : 0.8130513319772293
33 : 0.8129400133729977
34 : 0.8128294452363019
35 : 0.8127197041851856
36 : 0.8126108541327801
37 : 0.812502948048576
38 : 0.8123960294605085
39 : 0.8122901337400306
40 : 0.8121852892047272
41 : 0.8120815180669061
42 : 0.

In [25]:
for i in range(200,500):
    l1 = Lasso(alpha=i)
    l1.fit(X_train,y_train)
    print(i,":",l1.score(X_test,y_test))

200 : 0.813920135802378
201 : 0.8139280662762405
202 : 0.813935159660421
203 : 0.813941445241329
204 : 0.8139468631678922
205 : 0.8139514440169053
206 : 0.813955187854152
207 : 0.8139580947656482
208 : 0.8139601648600465
209 : 0.8139614191109495
210 : 0.8139618129219518
211 : 0.8139613886609692
212 : 0.8139601251073795
213 : 0.813958006711075
214 : 0.8139550662926405
215 : 0.8139512871144876
216 : 0.8139466685438559
217 : 0.8139412205900792
218 : 0.8139349321776366
219 : 0.8139278044131173
220 : 0.8139198412531332
221 : 0.813911039568461
222 : 0.8139013960835557
223 : 0.8138907327491184
224 : 0.8138793495175787
225 : 0.8138679413173151
226 : 0.8138517841273681
227 : 0.8138300965530063
228 : 0.813808862026844
229 : 0.8137720953012534
230 : 0.8137112454115849
231 : 0.8136506073167213
232 : 0.8135895879419386
233 : 0.8135281292925489
234 : 0.8134662345475688
235 : 0.8134039469376059
236 : 0.8133412664626606
237 : 0.8132781990167929
238 : 0.8132147054024553
239 : 0.8131507954227812
240 : 0

In [26]:
l2 = Ridge(alpha=11)
l2.fit(X_train,y_train)
print(l2.score(X_test,y_test))

0.8150277245431791


In [27]:
l2.coef_

array([ 2.08075572e+02, -4.19381533e-01,  3.60059061e+02,  5.73951520e+02,
        1.04837625e+02,  2.25081577e+01,  2.09621781e+02, -2.70364868e+02,
       -1.85682528e+02, -8.73561956e+02, -6.31723522e+02,  1.53165287e+03,
        2.37667318e+03,  5.13039213e+02])

In [28]:
l1 = Lasso(alpha=212)
l1.fit(X_train,y_train)
print(l1.score(X_test,y_test))

0.8139601251073795


In [29]:
l1.coef_

array([   0.        ,    2.06688612,  293.00804229,  475.74946113,
        116.54461228,   15.88311143,   18.71477938, -106.73349254,
       -165.63385126,   -0.        , -417.94284571, 1064.54140452,
       1219.50325351,  307.62453398])

## k-fold cross validation

In [30]:
from sklearn.model_selection import cross_val_score

In [35]:
l1_cross = cross_val_score(l1,X,y,cv=4)
print(l1_cross)

[0.76829534 0.81734961 0.43670651 0.44902514]


In [36]:
l2_cross = cross_val_score(l2,X,y,cv=4)
print(l2_cross)

[0.74102278 0.859919   0.40754955 0.45287323]


In [33]:
np.mean(l1_cross)

0.6178441498868896

In [34]:
np.mean(l2_cross)

0.6153411408406555